ALTER TABLE problems DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE step_evaluations DISABLE ROW LEVEL SECURITY;
ALTER TABLE review_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE learner_profiles DISABLE ROW LEVEL SECURITY;